---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        group-by: dependency-name
