name: all-tests
description: run all tests for ansible-rulebook (unit, integration, e2e)

runs:
  using: composite
  steps:
    - name: Setup jUnit reporter
      shell: bash
      run: |
        echo "GIT_SHA=$(git rev-parse "$GITHUB_SHA")" >> "$GITHUB_ENV"

    - name: Common tests
      env:
        PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_USER: ${{ env.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_USER }}
        PDE_ORG_RESULTS_UPLOAD_PASSWORD: ${{ env.PDE_ORG_RESULTS_UPLOAD_PASSWORD }}
        PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_URL: ${{ env.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_URL }}
      uses: ./.github/actions/common-tests

    - name: Long-running tests
      shell: bash
      run: pytest -m "long_run" -vv -n auto --cov=./ --cov-report=xml --cov-append --junit-xml=long-running-test-results.xml

    - name: Upload jUnit test results (APDE CI)
      shell: bash
      if: env.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_URL != '' && github.ref == 'refs/heads/main'
      run: >-
        http --check-status --ignore-stdin
        --auth "${{ env.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_USER }}:${{ env.PDE_ORG_RESULTS_UPLOAD_PASSWORD }}"
        -f POST "${{ env.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_URL }}/api/results/upload/"
        xunit_xml@long-running-test-results.xml
        component_name=eda
        git_commit_sha=${{ env.GIT_SHA }}
        git_repository_url="https://github.com/${{ github.repository }}"

    - name: e2e tests
      env:
        PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_USER: ${{ env.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_USER }}
        PDE_ORG_RESULTS_UPLOAD_PASSWORD: ${{ env.PDE_ORG_RESULTS_UPLOAD_PASSWORD }}
        PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_URL: ${{ env.PDE_ORG_RESULTS_AGGREGATOR_UPLOAD_URL }}
      uses: ./.github/actions/e2e-tests
