name: build-and-test-image
description: Build and test the container image

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Get package version
      shell: bash
      run: |
        python -m pip install setuptools_scm
        echo "SETUPTOOLS_SCM_PRETEND_VERSION=$(python -m setuptools_scm)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build container image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        tags: localhost/ansible-rulebook:test
        load: true
        build-args: |
          SETUPTOOLS_SCM_PRETEND_VERSION=${{ env.SETUPTOOLS_SCM_PRETEND_VERSION }}

    - name: Run tests
      shell: bash
      run: >
        docker run --rm localhost/ansible-rulebook:test bash -c '
        pip install -r requirements_test.txt &&
        pytest -m "e2e" -n auto'
