name: e2e-tests
description: run e2e tests for ansible-rulebook

runs:
  using: composite
  steps:
    - name: Run e2e tests
      shell: bash
      run: pytest -m "e2e" -n auto --cov=./ --cov-report=xml --cov-append
