name: run-isort
description: run isort

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      shell: bash
      run: python -m pip install isort

    - name: Lint with isort
      shell: bash
      run: isort . --check --diff
