name: Release Workflow

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Restrict this action only to protected tags
    if: github.repository == 'ansible/ansible-rulebook' && startsWith(github.event.release.tag_name, 'v')
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.0
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.0.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U build setuptools setuptools_scm

      - name: Build package
        run: make dist

      - name: Upload artifacts to GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          RELEASE_ID: ${{ github.event.release.id }}
        run: |
          gh release upload "$RELEASE_TAG" dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
